### ISSUE TITLE
Plain HTML

### ISSUE THREAD

**Issue by townmulti** [atulmy/meteor-baseui#1]
Great job on this baseui! Your hard work is appreciated. I've been trying to get it to work in regular HTML pages with just link tags in the head to the external js and css. I can see the isActiveRoute api is used, but is there a simple way I can get the simple HTML files for each page for ui without the Blaze integration? I'm trying to get it to work in React and Angular for meteor 1.3 on mobile web.

**Comment by atulmy** [comment]
@townmulti Glad you liked it. Sure, will isolate BaseUI from Meteor and put it in a separate repository by Sunday. Will keep you posted.

**Comment by townmulti** [comment]
Oh wow great! Thank you very much! :+1: :100:

**Comment by atulmy** [comment]
@townmulti here you go: https://github.com/atulmy/baseui sorry for the delay. Coming for AngularJS and ReactJS as well :smile:

**Comment by townmulti** [comment]
Fantastic! Thanks a lot for this! And awesome news for Angular & React😊
